/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChecklistStatusList: typeof import('./src/components/opportunity/ChecklistStatusList.vue')['default']
    EmailBatchSection: typeof import('./src/components/input/EmailBatchSection.vue')['default']
    InputErrorSummary: typeof import('./src/components/input/InputErrorSummary.vue')['default']
    OpportunityDetailsPanel: typeof import('./src/components/opportunity/OpportunityDetailsPanel.vue')['default']
    OpportunityRankedList: typeof import('./src/components/opportunity/OpportunityRankedList.vue')['default']
    OpportunityRankedListItem: typeof import('./src/components/opportunity/OpportunityRankedListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreIndicators: typeof import('./src/components/opportunity/ScoreIndicators.vue')['default']
    StudentProfileSection: typeof import('./src/components/input/StudentProfileSection.vue')['default']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_755778f5e6fed574cfd1ae152491355e/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_755778f5e6fed574cfd1ae152491355e/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_755778f5e6fed574cfd1ae152491355e/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UiBadge: typeof import('./src/components/ui/UiBadge.vue')['default']
    UiEmptyState: typeof import('./src/components/ui/UiEmptyState.vue')['default']
    UiErrorState: typeof import('./src/components/ui/UiErrorState.vue')['default']
    UiLoadingState: typeof import('./src/components/ui/UiLoadingState.vue')['default']
    UProgress: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_755778f5e6fed574cfd1ae152491355e/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
  }
}
